config/routes.rb
Rails.application.routes.draw do
  root to: 'directions#index'
  resources :directions
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

  def index
    @directions = Direction.all
  end

  def show
    @direction = Direction.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directions/index.html.erb
<div class="container">
    <h1>Directions</h1>

    <ul>
      <% @directions.each do |direction| %>
        <li><%= link_to direction.street, direction_path(direction) %></li>

       <% end %>
    </ul>


</div>

app/views/directions/show.html.erb
<div class="container">
  <h1><%= @direction.street %> <small><%= @direction.city %></small></h1>
    <%= @direction.outside_number %>
    <%= @direction.inside_number %>
    <%= @direction.cp %>
    <%= @direction.colonia %>
    <%= @direction.delegation %>
    <%= @direction.city %>
    <%= @direction.state %>
    <%= @direction.country %>
  
  <%=link_to "Back", directions_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Directions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>